---
- name: Get os release
  hosts: all
  tasks:
    - name: Get os release
      command: cat /etc/os-release
      register: os

    - name: Print OS release
      debug:
        msg: "OS: {{ os.stdout }}"

    - name: Set fact for OS
      set_fact:
        os_release: "{{ os.stdout }}"
