---
- hosts: all
  name: Host status
  tasks:

    - name: Get uptime
      command: uptime
      register: uptime
      changed_when: False

    - name: Show hostname and uptime
      ansible.builtin.debug:
        msg:
          - "Uptime: {{ uptime.stdout }}"
